// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/data.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataParser_Parse_FullMethodName = "/data.DataParser/Parse"
)

// DataParserClient is the client API for DataParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataParserClient interface {
	Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
}

type dataParserClient struct {
	cc grpc.ClientConnInterface
}

func NewDataParserClient(cc grpc.ClientConnInterface) DataParserClient {
	return &dataParserClient{cc}
}

func (c *dataParserClient) Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, DataParser_Parse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataParserServer is the server API for DataParser service.
// All implementations must embed UnimplementedDataParserServer
// for forward compatibility.
type DataParserServer interface {
	Parse(context.Context, *ParseRequest) (*ParseResponse, error)
	mustEmbedUnimplementedDataParserServer()
}

// UnimplementedDataParserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataParserServer struct{}

func (UnimplementedDataParserServer) Parse(context.Context, *ParseRequest) (*ParseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedDataParserServer) mustEmbedUnimplementedDataParserServer() {}
func (UnimplementedDataParserServer) testEmbeddedByValue()                    {}

// UnsafeDataParserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataParserServer will
// result in compilation errors.
type UnsafeDataParserServer interface {
	mustEmbedUnimplementedDataParserServer()
}

func RegisterDataParserServer(s grpc.ServiceRegistrar, srv DataParserServer) {
	// If the following call pancis, it indicates UnimplementedDataParserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataParser_ServiceDesc, srv)
}

func _DataParser_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataParserServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataParser_Parse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataParserServer).Parse(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataParser_ServiceDesc is the grpc.ServiceDesc for DataParser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataParser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.DataParser",
	HandlerType: (*DataParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _DataParser_Parse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/data.proto",
}
