# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sensor_analysis_pb2 as sensor__analysis__pb2


class SensorDataAnalysisServiceStub(object):
    """Simple service for basic statistical analysis of sensor data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSensorData = channel.unary_unary(
                '/ocean_analysis.SensorDataAnalysisService/AnalyzeSensorData',
                request_serializer=sensor__analysis__pb2.SensorDataRequest.SerializeToString,
                response_deserializer=sensor__analysis__pb2.SensorDataAnalysisResponse.FromString,
                )


class SensorDataAnalysisServiceServicer(object):
    """Simple service for basic statistical analysis of sensor data
    """

    def AnalyzeSensorData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorDataAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSensorData': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSensorData,
                    request_deserializer=sensor__analysis__pb2.SensorDataRequest.FromString,
                    response_serializer=sensor__analysis__pb2.SensorDataAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ocean_analysis.SensorDataAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SensorDataAnalysisService(object):
    """Simple service for basic statistical analysis of sensor data
    """

    @staticmethod
    def AnalyzeSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ocean_analysis.SensorDataAnalysisService/AnalyzeSensorData',
            sensor__analysis__pb2.SensorDataRequest.SerializeToString,
            sensor__analysis__pb2.SensorDataAnalysisResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
