# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_analysis.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15sensor_analysis.proto\x12\x0eocean_analysis\"6\n\x11SensorDataRequest\x12\x11\n\tdata_type\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x01\"w\n\x1aSensorDataAnalysisResponse\x12\x0f\n\x07\x61verage\x18\x01 \x01(\x01\x12\x0b\n\x03min\x18\x02 \x01(\x01\x12\x0b\n\x03max\x18\x03 \x01(\x01\x12\x0f\n\x07std_dev\x18\x04 \x01(\x01\x12\r\n\x05\x63ount\x18\x05 \x01(\x05\x12\x0e\n\x06median\x18\x06 \x01(\x01\x32\x7f\n\x19SensorDataAnalysisService\x12\x62\n\x11\x41nalyzeSensorData\x12!.ocean_analysis.SensorDataRequest\x1a*.ocean_analysis.SensorDataAnalysisResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_analysis_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENSORDATAREQUEST']._serialized_start=41
  _globals['_SENSORDATAREQUEST']._serialized_end=95
  _globals['_SENSORDATAANALYSISRESPONSE']._serialized_start=97
  _globals['_SENSORDATAANALYSISRESPONSE']._serialized_end=216
  _globals['_SENSORDATAANALYSISSERVICE']._serialized_start=218
  _globals['_SENSORDATAANALYSISSERVICE']._serialized_end=345
# @@protoc_insertion_point(module_scope)
